#!/usr/bin/env node

const ezs = require('ezs');
const basics = require('ezs-basics');
const istex = require('ezs-istex');

ezs.use(basics);
ezs.use(istex);

function str2qry(input, feed) {
  if (input) {
    feed.send({ q: input.trim() });
  } else {
    feed.send(input);
  }
};

process.stdin.resume();
process.stdin.setEncoding('utf8');
process.stdin
  .pipe(ezs('stringify'))
  .pipe(ezs(str2qry))
  .pipe(ezs('jsonify'))
  .pipe(process.stdout)
  ;
