#!/usr/bin/env node

const ezs = require('ezs');
const basics = require('ezs-basics');
const istex = require('ezs-istex');

ezs.use(basics);
ezs.use(istex);

process.stdin.resume();
process.stdin.setEncoding('utf8');
process.stdin
  .pipe(process.stdout)
;
