#!/usr/bin/env node

const ezs = require('ezs');
const basics = require('ezs-basics');
const istex = require('ezs-istex');

ezs.use(basics);
ezs.use(istex);

function str2qry(input, feed) {
  if (input) {
    feed.send({ q: input.trim() });
  } else {
    feed.send(input);
  }
};

const output = 'title,abstract';

const pick = require('lodash.pick');
function extract(input, feed) {
  if (input) {
    feed.send(pick(input.ISTEX, ['title', 'abstract']));
  } else {
    feed.send(input);
  }
};

process.stdin.resume();
process.stdin.setEncoding('utf8');
process.stdin
  .pipe(ezs('stringify'))
  .pipe(ezs(str2qry))
  .pipe(ezs('ISTEXQuery', { params: { output, }, }))
  .pipe(ezs('ISTEXRequest'))
  .pipe(ezs('ISTEXHits'))
  .pipe(ezs(extract))  
  .pipe(ezs('jsonify'))
  .pipe(process.stdout)
  ;
